/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Element;

/**
 *
 * @author User
 */
public class Tela extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());
    private Controle c;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        c = new Controle(this, jEditor, jAreaMensagem, jBarraStatus);
        LineNumberView lnv = new LineNumberView(jEditor);
        jScrollPane1.setRowHeaderView(lnv);
        atalhosTeclado();
    }
    
    public void mudaNomeDoc(){
        String nome = c.getDocumento().replace(".txt", "");
        jBarraStatus.setText("Arquivo: " + nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBotaoNovo = new javax.swing.JButton();
        jBotaoAbrirArquivo = new javax.swing.JButton();
        jBotaoSalvar = new javax.swing.JButton();
        jBotaoCopiar = new javax.swing.JButton();
        jBotaoColar = new javax.swing.JButton();
        jBotaoRecortar = new javax.swing.JButton();
        jBotaoCompilar = new javax.swing.JButton();
        jBotaoEquipe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAreaMensagem = new javax.swing.JTextArea();
        jBarraStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setResizable(false);

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(1204, 70));
        jToolBar1.setMinimumSize(new java.awt.Dimension(1204, 70));
        jToolBar1.setPreferredSize(new java.awt.Dimension(727, 28));

        jBotaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        jBotaoNovo.setText("Novo (ctrl + n)");
        jBotaoNovo.setFocusable(false);
        jBotaoNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoNovo.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoNovo.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoNovo.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoNovo);

        jBotaoAbrirArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open.png"))); // NOI18N
        jBotaoAbrirArquivo.setText("Abrir (ctrl + o)");
        jBotaoAbrirArquivo.setFocusable(false);
        jBotaoAbrirArquivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoAbrirArquivo.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoAbrirArquivo.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoAbrirArquivo.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoAbrirArquivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoAbrirArquivoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoAbrirArquivo);

        jBotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jBotaoSalvar.setText("Salvar (ctrl + s)");
        jBotaoSalvar.setFocusable(false);
        jBotaoSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoSalvar.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoSalvar.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoSalvar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoSalvar);

        jBotaoCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy.png"))); // NOI18N
        jBotaoCopiar.setText("Copiar (ctrl + c)");
        jBotaoCopiar.setFocusable(false);
        jBotaoCopiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoCopiar.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoCopiar.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoCopiar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoCopiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoCopiarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoCopiar);

        jBotaoColar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy (1).png"))); // NOI18N
        jBotaoColar.setText("Colar (ctrl + v)");
        jBotaoColar.setFocusable(false);
        jBotaoColar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoColar.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoColar.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoColar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoColar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoColarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoColar);

        jBotaoRecortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new.png"))); // NOI18N
        jBotaoRecortar.setText("Recortar (ctrl + x)");
        jBotaoRecortar.setFocusable(false);
        jBotaoRecortar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoRecortar.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoRecortar.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoRecortar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoRecortar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoRecortarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoRecortar);

        jBotaoCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilate.png"))); // NOI18N
        jBotaoCompilar.setText("Compilar (F7)");
        jBotaoCompilar.setFocusable(false);
        jBotaoCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoCompilar.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoCompilar.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoCompilar.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoCompilarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoCompilar);

        jBotaoEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group.png"))); // NOI18N
        jBotaoEquipe.setText("Equipe (ctrl + e)");
        jBotaoEquipe.setFocusable(false);
        jBotaoEquipe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBotaoEquipe.setMaximumSize(new java.awt.Dimension(150, 70));
        jBotaoEquipe.setMinimumSize(new java.awt.Dimension(150, 70));
        jBotaoEquipe.setPreferredSize(new java.awt.Dimension(150, 70));
        jBotaoEquipe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBotaoEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEquipeActionPerformed(evt);
            }
        });
        jToolBar1.add(jBotaoEquipe);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jEditor.setColumns(20);
        jEditor.setRows(25);
        jScrollPane1.setViewportView(jEditor);

        jSplitPane2.setTopComponent(jScrollPane1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jAreaMensagem.setColumns(20);
        jAreaMensagem.setEnabled(false);
        jAreaMensagem.setMinimumSize(new java.awt.Dimension(10, 20));
        jScrollPane2.setViewportView(jAreaMensagem);

        jSplitPane2.setBottomComponent(jScrollPane2);

        jBarraStatus.setText("'");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBarraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBarraStatus)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoNovoActionPerformed
        c.buttonNovo();
    }//GEN-LAST:event_jBotaoNovoActionPerformed

    private void jBotaoAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoAbrirArquivoActionPerformed
        c.buttonAbrir();
    }//GEN-LAST:event_jBotaoAbrirArquivoActionPerformed

    private void jBotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSalvarActionPerformed
        c.buttonSalvar(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBotaoSalvarActionPerformed

    private void jBotaoCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoCopiarActionPerformed
        c.buttonCopiar();
    }//GEN-LAST:event_jBotaoCopiarActionPerformed

    private void jBotaoColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoColarActionPerformed
        c.buttonColar();
    }//GEN-LAST:event_jBotaoColarActionPerformed

    private void jBotaoRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoRecortarActionPerformed
        c.buttonRecortar();
    }//GEN-LAST:event_jBotaoRecortarActionPerformed

    private void jBotaoCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoCompilarActionPerformed
        c.buttonCompilar(jEditor.getText());
    }//GEN-LAST:event_jBotaoCompilarActionPerformed

    private void jBotaoEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEquipeActionPerformed
        c.buttonEquipe();
    }//GEN-LAST:event_jBotaoEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAreaMensagem;
    private javax.swing.JLabel jBarraStatus;
    private javax.swing.JButton jBotaoAbrirArquivo;
    private javax.swing.JButton jBotaoColar;
    private javax.swing.JButton jBotaoCompilar;
    private javax.swing.JButton jBotaoCopiar;
    private javax.swing.JButton jBotaoEquipe;
    private javax.swing.JButton jBotaoNovo;
    private javax.swing.JButton jBotaoRecortar;
    private javax.swing.JButton jBotaoSalvar;
    private javax.swing.JTextArea jEditor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void atalhosTeclado() {
        //Obter o input e action do editor
        InputMap inputMap = jEditor.getInputMap(JComponent.WHEN_FOCUSED);
        ActionMap actionMap = jEditor.getActionMap();

        //NOVO : CTRL + N
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_DOWN_MASK), "novo");
        actionMap.put("novo", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonNovo();
            }
        });

        //ABRIR : CTRL + O
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_DOWN_MASK), "abrir");
        actionMap.put("abrir", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonAbrir();
            }
        });

        //SALVAR : CTRL + S
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK), "salvar");
        actionMap.put("salvar", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonSalvar(false);
            }
        });

        //SALVAR-COM0 : CTRL + SHIFT + S
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK | InputEvent.SHIFT_DOWN_MASK), "salvar como");
        actionMap.put("salvar como", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonSalvar(true);
            }
        });

        //COPIAR : CTRL + C
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_DOWN_MASK), "copiar");
        actionMap.put("copiar", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonCopiar();
            }
        });

        //COLAR : CTRL + V
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.CTRL_DOWN_MASK), "colar");
        actionMap.put("colar", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonColar();
            }
        });

        //RECORTAR : CTRL + X
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_X, InputEvent.CTRL_DOWN_MASK), "recortar");
        actionMap.put("recortar", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonRecortar();
            }
        });

        //COMPILAR : CTRL + E
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_E, KeyEvent.CTRL_DOWN_MASK), "compilar");
        actionMap.put("compilar", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonCompilar(jEditor.getText());
            }
        });

        //EQUIPE : F1
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0), "equipe");
        actionMap.put("equipe", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                c.buttonEquipe();
            }
        });
    }

    public class LineNumberView extends JComponent implements DocumentListener {

        private final JTextArea textArea;
        private final Font font = new Font(Font.MONOSPACED, Font.PLAIN, 12);

        public LineNumberView(JTextArea textArea) {
            this.textArea = textArea;
            textArea.getDocument().addDocumentListener(this);
            setFont(font);
            setPreferredSize(new Dimension(40, Integer.MAX_VALUE));
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            FontMetrics fm = g.getFontMetrics(font);
            int lineHeight = fm.getHeight();

            Rectangle clip = g.getClipBounds();
            int startOffset = textArea.viewToModel2D(new Point(0, clip.y));
            int endOffset = textArea.viewToModel2D(new Point(0, clip.y + clip.height));

            Element root = textArea.getDocument().getDefaultRootElement();
            int startLine = root.getElementIndex(startOffset);
            int endLine = root.getElementIndex(endOffset);

            for (int line = startLine; line <= endLine; line++) {
                try {
                    Rectangle r = textArea.modelToView2D(root.getElement(line).getStartOffset()).getBounds();
                    int y = r.y + r.height - fm.getDescent();
                    String num = String.valueOf(line + 1);
                    g.drawString(num, getWidth() - fm.stringWidth(num) - 5, y);
                } catch (Exception ex) {

                }
            }
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            repaint();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            repaint();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            repaint();
        }
    }
}
